name: CI Pipeline

on: workflow_dispatch

jobs:
  build:
    # Use your own runner environment
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a build script
        run: echo "Running on my own custom infrastructure!"

      - name: Printing HostName
        run: hostnamectl
