name: GitHub Action Variable And Secret Demo
on: workflow_dispatch

env:
 Global_Var: "Hi, I am available EveryWhere"

jobs:
  variable_demo:
        runs-on: ubuntu-latest
        env:
          Job_var: "Hi, I am available on This Variable Demo Job Level Only"
        steps:
          - name: Print Global Variable
            env:
              Step_Var: "Hellow, I am Available only to this Step"    
            run: |
               echo "Global: $Global_Var"
               echo "Job: $Job_var"
               echo "Step: $Step_Var"
  
  secret_demo:
          runs-on: ubuntu-latest
          steps:
             - name: Printing Repo Secret
               run: echo "My demo repository secret is ${{ secrets.demo_secret }}"
   
  single_job:
          runs-on: ubuntu-latest
          steps:
            - name: Generate Value
              run: echo "My_Var=Hellow From Step 1" >> $GITHUB_ENV
      
            - name: Read Value
              run: echo "The Variable is ${{ env.My_Var }}"

            - name: Generate OutPut
              id: producer_step
              run: echo "my_output=secretValue" >> $GITHUB_OUTPUT

            - name: Read OutPut
              run: echo "The output is ${{ steps.producer_step.outputs.my_output }}"
              

            

      