name: GitHub Action Variable And Secret Demo
on: workflow_dispatch

env:
 Global_Var: "Hi, I am available EveryWhere"

jobs:
  variable_demo:
        runs-on: ubuntu-latest
        env:
          Job_var: "Hi, I am available on This Variable Demo Job Level Only"
        steps:
          - name: Print Global Variable
            env:
              Step_Var: "Hellow, I am Available only to this Step"    
            run: |
               echo "Global: $Global_Var"
               echo "Job: $Job_var"
               echo "Step: $Step_Var"

      